### ISSUE TITLE
The pop-up of version 1.85 (alpha) makes the game window move into the background

### ISSUE THREAD

**Issue by PlageOne** [SteamAchievementNotifier/SteamAchievementNotifier#45]
Hi hi,

I have a strange problem with the new alpha version of your still very good tool.

The pop-up of version 1.85 (alpha) makes the game window move into the background. Interaction is then only possible again when you click on the game with the mouse and bring it back to the foreground.

With the "old" version 1.84, I can not confirm the problem and is not present in my opinion there.
 However, I have only tested both versions with the game "Gylt".

Greetings

Plage

**Comment by SteamAchievementNotifier** [comment]
Hey @PlageOne,

Thanks for checking out the Alpha! I pushed the first update yesterday in which I included a potential fix for this, which works for me, but others have advised they are still having the issue after updating.

I believe it is an issue within the Tauri framework used in the new version, which I have reported [here](https://github.com/tauri-apps/tauri/issues/7519), but can you confirm you're on the latest update? It should be `1.85.1`, which can be seen at the bottom of the **Settings** menu if you've updated.

Thanks!

**Comment by PlageOne** [comment]
Hey,

Thanks for your answer. 
I was just able to test the new version 1.85.1 and the problem seems to be fixed with this version.

About something else:

(Is only a guess and can be only coincidence).

I think the tool has a problem with an installaion into a separate folder. 
I think you have to install the alpha version 1.85.X in the default folder to avoid further errors and problems.

Example Custom folder: D:\Games\Tools\SteamAchievementNotifier

After I updated from version 1.85 to 1.85.1 nothing worked with your tool.

- The options could no longer be opened, the window was only dark and then nothing happened at all.
- The red exclamation mark (log file) could no longer be opened.
- I could not select a sound file anymore, because the selection window did not open any more
- The customiser did not open anymore either.

To make it short: Only the main window opened but everything else did not work.

However, after I did a complete reinstallation of the tool with the default installation path, the program ran, completely without error messages.
At least until now :P

Greetings

Plage

**Comment by SteamAchievementNotifier** [comment]
Hey again @PlageOne,

Glad the first issue is resolved for you! I pushed an update about an hour ago to address the installation path issue, so that should also now be resolved too.

Let me now if you have any further issues!

Thanks!

**Comment by tristanc95** [comment]
Hi there! Sorry to just bump in on this thread, but I'm having the same issue still on 1.85.2 where when an achievement unlocks it seems to move the game to the background or just out of the screen for a second. I also do have this installed I believe in the default location rather than another location or drive.

I've played 2 games so far with this new update (Evil West & Lost Judgment) and they both have run into that issue where when an achievement pops, the game seems to lose active window. 

I did not have this on 1.84 from what I can remember through all the games I used it with so I'm guessing it's something with the newer version.  Please let me know if you need anything for me to send and I'm more than happy to c:

**Comment by SteamAchievementNotifier** [comment]
Hey @tristanc95 - thanks for letting me know. I've had a few users with this same issue, so I'm awaiting a response from the Tauri devs regarding this. It seems to be affecting different games for different people, so could be a graphics API thing, but the games I've tested with don't seem to have this issue for me, at least.

Either way, I'll be looking into a way to resolve it, so I'll update you with any progress 👍

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Hey @tristanc95,

I've pushed an update to V1.85.3 which targets focusing issues. If you could let me know if the issue is resolved, I would be grateful.

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Hey again @tristanc95,

I'll close this issue as there's been no response and the original issue was confirmed to be resolved, but feel free to open a new issue or join the Discord if you're still having problems with it.

Thanks!
